config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users do
    member do
      get :followings, :followers
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 140}
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save {self.email = self.email.downcase}
    validates :name, presence: true, length: {maximum: 50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
    validates :introduction, length: {maximum: 100}
    VALID_WEBSITE_REGEX = /https?:\/\/[\S]+/
    validates :website, format: {with: VALID_WEBSITE_REGEX}, allow_blank: true, on: :update
    validates :location, length: {minimum: 2, maximum: 20}, allow_blank: true, on: :update
    validates :birthday, :introduction, :location, :website, absence: true, on: :create
    validates :introduction, length: {maximum: 100}, allow_blank: true, on: :update

    has_secure_password
    
    has_many :microposts
    has_many :following_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
    has_many :following_users, through: :following_relationships, source: :followed
    has_many :follower_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
    has_many :follower_users, through: :follower_relationships, source: :follower
    
    def follow(other_user)
        following_relationships.find_or_create_by(followed_id: other_user.id)
    end
    
    def unfollow(other_user)
        following_relationship = following_relationships.find_by(followed_id: other_user.id)
        following_relationship.destroy if following_relationship
    end
    
    def following?(other_user)
        following_users.include?(other_user)
    end
    
    def feed_items
        Micropost.where(user_id: following_user_ids + [self.id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only: [:create]
    
    def create
        @micropost = current_user.microposts.build(micropost_params)
        if @micropost.save
            flash[:success] = "Micropost created!"
            redirect_to root_url
        else
            @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc)
            render 'static_pages/home'
        end
    end
    
    def destroy
        @micropost = current_user.micropost.find_by(id: params[:id])
        return redirect_to root_url if @micropost.nil?
        @micropost.destroy
        flash[:success] = "Micropost deleted"
        redirect_to request.referrer || root_url
    end
        
    private
    def micropost_params
        params.require(:micropost).permit(:content)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :logged_in_user
    
    def create
        @user = User.find(params[:followed_id])
        current_user.follow(@user)
    end
    
    def destroy
        @user = current_user.following_relationships.find(params[:id]).followed
        current_user.unfollow(@user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = "invalid email/password combination"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build if logged_in?
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_params, only: [:show, :edit, :update]
  before_action :correct_user, only: [:edit, :update]
  
  def show
    @microposts = @user.microposts.order(created_at: :desc)
  end
  
  def new
    @user = User.new
    @submit = 'Save'
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def followings
    @title = "followings"
    @user = User.find(params[:id])
    @users = @user.following_users
    render 'show_follow'
  end
  
  def followers
    @title = "followers"
    @user = User.find(params[:id])
    @users = @user.follower_users
    render 'show_follow'
  end

  def edit
    @submit = 'Update'
  end
  
  def update
    if @user.update(user_params)
      redirect_to @user
      flash[:success] = "Your Profile has been edited"
    else
      render 'edit'
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :birthday, :introduction, :location, :website)
  end
  
  def set_params
    @user = User.find(params[:id])
  end

  def correct_user
    redirect_to root_path if @user != current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !!current_user
    end
    
    def store_location
        session[:forwarding_url] = request.url if request.get?
    end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Microposts", root_path , id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li>
            <%= link_to "Home", root_path %>
        </li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Profile", current_user %>
              </li>
              <li>
                <%= link_to "Settings", edit_user_path(current_user) %>
              </li>
              <li class="divider"></li>
              <li>  
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to "Log in", login_path %>
          </li> 
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microposts</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>" >
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>

  <span class="user">
    <%= link_to micropost.user.name, micropost.user %>
  </span>
  <span class="content">
    <%= micropost.content %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user == micropost.user %>
        <%= link_to "delete", micropost, method: :delete, data: {confirm: "Are you sure?"} %>
    <% end %>  
  </span>
</li>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains 
    <%= pluralize(object.errors.count, "error") %>
.
    </div>
    <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>
                <%= msg %>
            </li>
        <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="microposts">
        <%= render @feed_items %>
    </ol>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
        <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>

<h1>
    <%= current_user.name %>
</h1>
<span>
    <%= link_to "view my profile", current_user %>
</span>
<span>
    <%= pluralize(current_user.microposts.count, "micropost") %>
</span>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form"> 
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3> 
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Microposts</h1>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
    <div>
        <%= hidden_field_tag :followed_id, @user.id %>
    </div>
  
    <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
        <%= render 'unfollow' %>
    <% else %>
        <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
            
            <% if controller.controller_name == 'users' &&
                (controller.action_name == 'update' ||  controller.action_name == 'edit') %>
            
              <%= f.label :birthday %>
              <%= f.date_select :birthday, start_year: 1990, class: "form-control" %>
              
              <%= f.label :introduction %>
              <%= f.text_area :introduction, class: "form-control" %>
              
              <%= f.label :location %>
              <%= f.text_field :location, class: "form-control" %>
              
              <%= f.label :website %>
              <%= f.text_field :website, class: "form-control" %>

            <% end %>
            
            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control" %>
            
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control" %>
            
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
            
            <%= f.submit @submit, class: "btn btn-large btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
             
    <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li id="follow-user">
  <%= link_to gravatar_for(user, size: 50), user %>
  
  <span class="user">
    <%=link_to user.name, user %>
  </span>
</li>

app/views/users/_user_info.html.erb
<section class="user_info">
  <h1>
    <%= gravatar_for @user %>
    <%= @user.name %>
    <div class="follow">
      <a href="<%= followings_user_path(@user) %>">
        <%= @user.following_users.count %> following
      </a>
      <a href="<%= followers_user_path(@user) %>">
        <%= @user.follower_users.count %> followers
      </a>
    </div>
  </h1>
  <div class ="extra_info">
    <ol>Birthday: <%= @user.birthday %></ol>
    <ol>Introduction: <%= @user.introduction %></ol>
    <ol>Location: <%= @user.location%></ol>
    <ol>Website: <%= @user.website %></ol>
  </div>
  <%= link_to "Edit Profile", edit_user_path %>
</section>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render 'user_info' %>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
        <h3>Microposts (<%= @user.microposts.count %>)</h3>
        <ol class="microposts">
            <%= render @microposts %>
        </ol>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render 'user_info' %>
  </aside>
  <div class="col-md-8">

    <h3><%= @title %> (<%= @users.count %>)</h3>
    <ul class="follow">
        <%= render @users %>
    </ul>
  </div>
</div>

<%#= render partial: 'users/user', collection: @users %>